version: '3.8'

services:

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=v1.2.0
    container_name: nodejs.compose
    environment:
      - PORT=5000
    ports:
      - "5055:5000"

  flaskapp:
    build:
      context: /home/skylab027/Desktop/Docker/Curso_Docker/Udemy/mod_7/Build_py
      dockerfile: Dockerfile
    container_name: flask.compose
    ports:
      - "5056:5000"
    depends_on:
      - nodeapp